# Generated by Django 4.1.5 on 2023-02-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_addr',
            new_name='eaddr',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='eno',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_sal',
            new_name='esal',
        ),
    ]
