# Generated by Django 3.2.9 on 2022-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Title', models.CharField(max_length=64)),
                ('Author', models.CharField(max_length=64)),
                ('Publish_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Account_Number', models.IntegerField()),
                ('Mail_Id', models.CharField(max_length=64)),
                ('Phone_Number', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_No', models.IntegerField()),
                ('Eoployee_Name', models.CharField(max_length=64)),
                ('Employee_Salary', models.FloatField()),
                ('Employee_Address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posting_Date', models.DateField()),
                ('Location', models.CharField(max_length=54)),
                ('Offered_Salary', models.FloatField()),
                ('Qualification', models.CharField(max_length=54)),
            ],
        ),
    ]
