# Generated by Django 3.2.9 on 2022-09-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='EMPLOYEE',
        ),
    ]
