# Generated by Django 3.2.9 on 2022-09-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20220901_1716'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='BOOKS',
        ),
        migrations.AlterModelTable(
            name='customers',
            table='CUSTOMERS',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='JOBS',
        ),
    ]
