# Generated by Django 4.1.5 on 2023-01-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_name_studentmodel_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='First_Name',
            new_name='Name',
        ),
    ]
