# Generated by Django 4.1.5 on 2023-01-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_first_name_studentmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Name',
            new_name='First_Name',
        ),
    ]
