# Generated by Django 3.2.9 on 2022-08-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_book_customer_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
