# Generated by Django 4.1.5 on 2023-01-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('MovieName', models.CharField(max_length=30)),
                ('Hero', models.CharField(max_length=30)),
                ('Heroine', models.CharField(max_length=30)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
