# Generated by Django 4.1.5 on 2023-12-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_studentuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
