# Generated by Django 4.1.4 on 2023-12-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country_table',
        ),
    ]
