# Generated by Django 4.1.4 on 2023-12-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_state_distric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distric',
            table='district_table',
        ),
        migrations.AlterModelTable(
            name='state',
            table='state_table',
        ),
    ]
