# Generated by Django 4.1.4 on 2023-12-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_distric_table_alter_state_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distric',
            new_name='District',
        ),
    ]
